"""Build technical note v1 (M5) from files on disk only. Every number is computed here from:
matlab_native/MATLAB_NATIVE_RESULTS.json, octave/comparison.json, outputs/*/result.json,
diag/outputs_diag/{validation,m3_case,voi,voi_A1,structural}.json, regions*.csv.
Writes note_v1.tex (compiled to note_v1.pdf by the caller) and NUMBERS.json (for the verifier)."""
from pathlib import Path
import json, shutil
import pandas as pd

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
D = PKG / 'diag' / 'outputs_diag'
J = lambda p: json.loads(Path(p).read_text())

ml = J(PKG / 'matlab_native' / 'MATLAB_NATIVE_RESULTS.json')
fr = ml['fresh_session_results']
val = J(D / 'validation.json')
m3 = J(D / 'm3_case.json')
voi, voiA = J(D / 'voi.json'), J(D / 'voi_A1.json')
st = J(D / 'structural.json')
cs2t = J(PKG / 'outputs' / 'CS2T_extended' / 'result.json')['tracking']
step = J(PKG / 'outputs' / 'STEP' / 'result.json')['dynamics']
reg, regA = pd.read_csv(D / 'regions.csv'), pd.read_csv(D / 'regions_A1.csv')

N = {}
def put(k, v):
    N[k] = v
    return v

# ---- M1 numbers
put('ml_max_dH2', max(fr[c]['max_dH2_pct_nominal_vs_python'] for c in ('STEP', 'CS1', 'CS2T', 'CS2P')))
put('ml_max_dIAE', max(fr[c]['IAE_rel_diff_pct'] for c in ('CS1', 'CS2T', 'CS2P')))
for c in ('CS1', 'CS2T', 'CS2P'):
    put(f'ml_{c}_vs_pub', fr[c]['matlab_vs_published_pct'])
put('cs1_contaminated', ml['contaminated_first_session']['CS1_vs_published_pct'])
put('gap_ratio_cs2t', (2.62e-4 - cs2t['conventional_iae_mol']) / (2.76379e-4 * .1))
put('step_tau', step['tau_min']); put('step_delay', step['delay_min'])

# ---- M2-M4 numbers
put('V1_C', val['V1']['C']['max_dH2_pct_nominal']); put('V1_M', val['V1']['M']['max_dH2_pct_nominal'])
put('V2_max', max(val['V2'][k]['dH2_pct_nominal'] for k in ('C', 'M')))
put('thC', m3['theta']['C']); put('thM', m3['theta']['M'])
ps = {p['feature']: p for p in m3['per_sensor_S4']}
put('m3_move_sd', abs(ps['H2_mol_min']['move_residual'] / ps['H2_mol_min']['move_sd_of_difference']))
put('m3_ch4_sd', ps['y_CH4']['residual_after_bias_in_sd'])
put('m3_lambda_E5', m3['stopping_rule_C_vs_M']['truth_C_S1']['E5']['lambda']['M'])
put('m3_lambda_E5_M', m3['stopping_rule_C_vs_M']['truth_M_S1']['E5']['lambda']['C'])
put('m3_keq', m3['membrane_equivalent_rate_per_min'])
put('move_cost', m3['move_cost_ethanol_mol'])


def frac(df, mode, s, mv):
    d = df[(df.scale == 1.0) & (df['mode'] == mode) & (df.set == s) & (df.move == mv) & (df.region != 'UNREACHABLE')]
    return int((d.region == 'DISTINGUISHABLE').sum()), int((d.region == 'DIFFERENT_ACTION').sum()), len(d)


rows = []
for mode in (1, 2):
    for s in ('S1', 'S2', 'S3', 'S4'):
        for mv in (False, True):
            a, b, n = frac(reg, mode, s, mv); a1, b1, _ = frac(regA, mode, s, mv)
            rows.append((mode, s + ('+E' if mv else ''), n, a, b, a1, b1))
            put(f'dist_m{mode}_{s}{"E" if mv else ""}', [a, b, a1, b1, n])
for mode in (1, 2):
    for key in ('S1+E', 'S3', 'S4', 'S4+E'):
        put(f'voiA_m{mode}_{key}_H2', voiA[f'mode{mode}_scale1.0_{key}']['H2_shortfall_avoided_mol_min'])
        put(f'voiA_m{mode}_{key}_EtOH', voiA[f'mode{mode}_scale1.0_{key}']['ethanol_excess_avoided_mol_min'])
        put(f'voi_m{mode}_{key}_EtOH', voi[f'mode{mode}_scale1.0_{key}']['ethanol_excess_avoided_mol_min'])
put('payback_min_m1', N['move_cost'] / N['voiA_m1_S1+E_EtOH'])
put('rank_m1_S1E', st['1']['S1+E']['rank_1e-6']); put('rank_m1_S4E', st['1']['S4+E']['rank_1e-6'])
put('rank_m2_S4', st['2']['S4']['rank_1e-6']); put('rank_m2_S4E', st['2']['S4+E']['rank_1e-6'])
sens = {}
for sc in (.5, 2.0):
    d = regA[(regA.scale == sc) & (regA.region != 'UNREACHABLE') & (regA.set == 'S1') & (regA.move)]
    sens[sc] = (int((d.region == 'DISTINGUISHABLE').sum()), len(d))
put('sens_half', list(sens[.5])); put('sens_double', list(sens[2.0]))

f2 = lambda x: f'{x:.2f}'
f3 = lambda x: f'{x:.3f}'
f4 = lambda x: f'{x:.4f}'
um = lambda x: f'{1e6 * x:.1f}'

table_rows = '\n'.join(f'{m} & {s} & {n} & {a} & {b} & {a1} & {b1} \\\\' for m, s, n, a, b, a1, b1 in rows)

TEX = r'''\documentclass[10pt,a4paper]{article}
\usepackage[margin=2.2cm]{geometry}
\usepackage{graphicx,booktabs,amsmath,hyperref,caption}
\captionsetup{font=small}
\title{When is knowing the cause worth the measurement?\\\large Degradation diagnosis on the SSMR ethanol-reforming benchmark (technical note v1, draft)}
\author{Bosco Chiramel\thanks{Draft prepared with AI assistance (Claude); every number is generated by scripts in the accompanying repository and checked by a verifier script. To be rewritten by the author before any release.}}
\date{30 September 2026 --- DRAFT, not released}
\begin{document}\maketitle
\begin{abstract}\noindent
When delivered hydrogen falls in a membrane reformer, can an operator tell catalyst deactivation from membrane fouling, feed shortfall or hydrogen-meter drift, and does it matter for what they do next?
On the published SSMR benchmark (Arcila-Osorio et al., 2026), reproduced in Python and checked against the authors' code in MATLAB (largest hydrogen difference <<ml_max_dH2>>\% of nominal), we map each cause and loss level to three regions: distinguishable, indistinguishable with the same action, and indistinguishable with a different action.
With the hydrogen flow alone none of the reachable scenarios is distinguishable, because a slow meter drift can mimic any process loss and calls for the opposite action.
A bounded six-minute feed move of +0.0003 mol/min, costing <<move_cost>> mol of ethanol, separates catalyst from membrane loss at a 5\% hydrogen drop by <<m3_move_sd>> noise standard deviations and resolves most losses of 5\% or more, while extra steady sensors without the move add less.
These are simulation results on the authors' exponential deterioration mechanisms with a declared noise model; no 1\% loss is distinguishable under any measurement set tested.
\end{abstract}

\section{Problem}
The benchmark of Arcila-Osorio, Destro, Ocampo-Martinez, Llorca and Braatz \cite{bench} provides a validated dynamic model of a two-stage staged-separation membrane reactor, six control challenges and deterioration scenarios in which all kinetic pre-factors decay as $e^{-0.01t}$ (catalyst) or the permeance pre-factor as $e^{-0.006t}$ (membrane), $t$ in minutes. The authors state that catalyst activity and membrane permeability are treated as run-invariant ``(i.e., no explicit deactivation, fouling, or aging kinetics)'' and that the release is deterministic, without sensor noise \cite{bench}. Challenge 4 notes that ``the catalyst activity is not measured''. This note works inside that stated gap. The question is a decision, not an estimation exercise: \emph{when delivered hydrogen falls, when is identifying the cause worth the measurement, and what is the least disruptive experiment that identifies it?}

\section{Prior work}
Serra, Ocampo-Martinez, Li and Llorca \cite{serra} designed linear MPC for an ethanol steam reformer with Pd-Ag membrane separation on a model fitted to the same group's experiments; they do not address degradation diagnosis. Scott, Findeisen, Braatz and Raimondo \cite{scott} and Raimondo, Marseglia, Braatz and Scott \cite{raimondo} design open- and closed-loop inputs that guarantee fault diagnosis for faults modelled as switches between linear systems with bounded uncertainty (zonotopes). The feed move below is an active-diagnosis input in their sense. What this note adds is narrower and practical: a computed map, on this nonlinear benchmark, of where the cause is identifiable from the signals an operator has, where the distinction changes the operating action, and what a one-step bounded move buys in operator units. We make no claim about optimal input design. The broader fault-diagnosis benchmark literature was not surveyed for this draft (see Limitations).

\section{Baseline reproduction (M1)}
The released MATLAB code (commit c628084) was run untouched in MATLAB R2026a for the four reference cases; only the README case settings were changed, in copies. A vectorised Python port of the same equations was compared on matched samples (Table~\ref{tab:m1}). Every approved equivalence gate passes: largest hydrogen difference <<ml_max_dH2>>\% of nominal (gate 0.5\%), largest IAE difference <<ml_max_dIAE>>\% (gate 1\%).

\begin{table}[h]\centering\small
\caption{Native MATLAB versus Python port, and MATLAB versus the paper's reported IAE.}\label{tab:m1}
\begin{tabular}{lrrrr}\toprule
case & max $\Delta$H$_2$ (\% nom.) & max $\Delta$EtOH (\% nom.) & IAE diff (\%) & MATLAB IAE vs paper \\\midrule
STEP & <<STEP_dH>> & <<STEP_dU>> & -- & -- \\
CS1 & <<CS1_dH>> & <<CS1_dU>> & <<CS1_dI>> & <<ml_CS1_vs_pub>>\% \\
CS2T & <<CS2T_dH>> & <<CS2T_dU>> & <<CS2T_dI>> & <<ml_CS2T_vs_pub>>\% \\
CS2P & <<CS2P_dH>> & <<CS2P_dU>> & <<CS2P_dI>> & <<ml_CS2P_vs_pub>>\% \\\bottomrule
\end{tabular}\end{table}

Case study 1 reproduces the paper. The disturbance cases do not, in MATLAB either, so the difference is between the released code and the paper, not in the port. For CS2T the gap equals <<gap_ratio_cs2t>> times one 0.1-min sample of full set-point error at the steam-only start; this pattern was found after the comparison and is a question for the authors, not a pass. The paper's ``time constant 0.25~min'' is not what a first-order-plus-dead-time fit returns (<<step_tau>>~min with <<step_delay>>~min dead time); the elapsed time from the input change to 63.2\% of the rise is close to 0.25~min. Two further findings: \texttt{control.m} keeps PID state in persistent variables that the script's \texttt{clear} does not reset, so running cases back to back moved CS1's IAE by <<cs1_contaminated>>\%; and GNU Octave's \texttt{ode15s} ignores the \texttt{NonNegative} option and cannot integrate the Mode~2 steam-only start, so Octave is not a substitute reference for Mode~2.

\section{Method (M2--M4)}
\textbf{Quasi-steady map.} Deterioration is slow against the reactor response, so steady states were computed on a grid of catalyst multiplier $a_c$, membrane multiplier $a_m$ (0.4--1) and ethanol feed (0.0018--0.0024 mol/min), 210 points, all converged, and interpolated. Gate V1: against full dynamic runs of the authors' two deterioration schedules over 20~min the map differs by at most <<V1_C>>\% (catalyst) and <<V1_M>>\% (membrane) of nominal hydrogen (gate 0.5\%). Gate V2: held-out points differ by at most <<V2_max>>\%. (Figure~\ref{fig:v1}.)

\textbf{Measurement layer.} Declared scenario values, not instrument specifications: hydrogen flow noise 0.5\% of nominal with an unknown constant bias of up to 0.5\%; outlet temperature 0.5~K noise, 1~K bias; waste-gas flow 1\%/2\%; micro-GC mole fractions of H$_2$, CH$_4$, CO, CO$_2$ at 1\% relative noise, 2\% bias, every 3~min with 3~min delay; a 10-min decision window. Measurement sets: S1 = H$_2$ flow; S2 = + outlet temperature; S3 = + waste flow; S4 = + mole fractions; ``+E'' adds the feed move (+0.0003 mol/min held 5~min after 1~min settling).

\textbf{Hypotheses and test.} Catalyst loss, membrane loss, feed shortfall (delivered ethanol a fraction of the command) and additive hydrogen-meter drift, each with one scalar severity, set to give 1, 2, 5, 10 or 20\% hydrogen drop at the mode's nominal feed. For each alternative cause the severity that best explains the data is fitted; its bias-robust statistic $\Lambda$ is compared with a $\chi^2_{0.99}$ threshold. The frozen protocol used $k-1$ degrees of freedom; because this penalises larger sensor sets, a dated amendment (A1) with one degree of freedom is reported beside it. Local structural identifiability: the noise-scaled sensitivity matrix has rank <<rank_m1_S1E>> for S1+E and <<rank_m1_S4E>> for S4+E in Mode~1 (four parameters).

\textbf{Actions.} For a process loss, the operator raises ethanol to restore the set-point if that is feasible within the 0.0024~mol/min bound; otherwise the component must be serviced. For meter drift, the action is to recalibrate and not change the feed. Costs of acting on the wrong cause are hydrogen shortfall or wasted ethanol, in mol/min.

\section{Results}
\textbf{Worked ambiguity case (M3).} In Mode~1 at 0.0021~mol/min, catalyst activity <<thC>> and membrane factor <<thM>> both give a 5\% hydrogen drop. Hydrogen, outlet temperature and waste flow differ by less than the bias bound; methane mole fraction differs by <<m3_ch4_sd>> noise units after bias. After the feed move, the hydrogen response differs by <<m3_move_sd>> standard deviations of the measured difference; $\Lambda$ for the wrong cause is <<m3_lambda_E5>> (truth catalyst) and <<m3_lambda_E5_M>> (truth membrane), above the threshold of 6.63, so the stopping rule declares the right cause after 5~min for every measurement set (Figure~\ref{fig:m3}). Over 30~min, the authors' catalyst schedule $e^{-0.01t}$ produces the same hydrogen signal as a membrane decaying at only <<m3_keq>>/min: hydrogen here is far more sensitive to the membrane than to the catalyst, which is why the catalyst cannot reach a 20\% hydrogen drop inside the tested range.

\textbf{Operating map (M4).} Table~\ref{tab:map} counts the reachable scenarios (four causes, five loss levels) per set. With S1 no scenario is distinguishable in either mode, under either threshold. The feed move is what changes the picture (Figure~\ref{fig:map}). No 1\% loss is distinguishable under any set or threshold. Under A1 with halved or doubled noise, S1+E distinguishes <<sens_half_0>> and <<sens_double_0>> of the <<sens_half_1>> reachable scenarios across both modes (<<sens_base>> at nominal noise).

\begin{table}[h]\centering\small
\caption{Reachable scenarios that are distinguishable (D) or indistinguishable with a different action (X), frozen threshold and amendment A1.}\label{tab:map}
\begin{tabular}{llrrrrr}\toprule
mode & set & $n$ & D frozen & X frozen & D (A1) & X (A1) \\\midrule
<<TABLE_ROWS>>
\bottomrule\end{tabular}\end{table}

\textbf{Value of information (Figure~\ref{fig:voi}).} Averaged over the scenarios, and relative to S1, the feed move avoids <<voiA_m1_S1E_EtOH>>~$\mu$mol/min of wasted ethanol and <<voiA_m1_S1E_H2>>~$\mu$mol/min of hydrogen shortfall in Mode~1 (A1), and <<voiA_m2_S1E_EtOH>> and <<voiA_m2_S1E_H2>>~$\mu$mol/min in Mode~2. The move itself costs <<move_cost>>~mol of ethanol, repaid in about <<payback>>~min of avoided waste in Mode~1. Adding waste flow and mole fractions without the move avoids <<voiA_m1_S4_EtOH>>~$\mu$mol/min in Mode~1: the move is worth more than the extra sensors.

\section{What to measure next on the rig}
On the authors' Pd-Ag rig: at steady operation, record permeate hydrogen (Bronkhorst meter) for 10~min, step ethanol by +0.0003~mol/min for 6~min, return. Predicted responses under each cause come from \texttt{diag/m3\_case.py}. Declare catalyst or membrane loss when exactly one hypothesis survives the $\Lambda$ test; if both survive, repeat with a 10-min hold; if both still survive, report ``deteriorated, cause not established''. Recalibrating the hydrogen meter against the soap-bubble retentate balance before the move removes the drift hypothesis, which is the most costly confusion in the map.

\section{Limitations (a hostile reviewer's list)}
\begin{enumerate}\itemsep0pt
\item \emph{Simulation only.} No experimental data; the deterioration laws are the authors' scenarios, not lifetime models. Conceded.
\item \emph{Noise and bias values are declared, not measured.} Sensitivity at $\times0.5$ and $\times2$ is reported; instrument data would replace them.
\item \emph{Quasi-steady approximation.} Checked against full dynamics (V1) for Mode~1 only.
\item \emph{Threshold choice.} The frozen rule penalises extra sensors; A1 is post-hoc. Both are shown; the main conclusions hold under both.
\item \emph{Paper mismatch.} CS2T/CS2P and the time constant do not match the paper, in MATLAB too; the author questions are open.
\item \emph{Single faults, np = 50, Modes 1--2.} Simultaneous faults, the fine grid and Mode~3 are not covered.
\item \emph{Related work.} Only the four papers cited were read; a wider fault-diagnosis sweep is pending.
\item \emph{Estimator and controller} (M6, M7) are first versions in the repository, not part of this note's claims.
\end{enumerate}

\section*{Reproducibility}
One command rebuilds every number (\texttt{run\_all.py}); protocols are frozen and hashed before results; \texttt{verify\_note.py} asserts every number in this note against the output files. Upstream code: MIT licence.

\begin{thebibliography}{9}\small
\bibitem{bench} M.~Arcila-Osorio, F.~Destro, C.~Ocampo-Martinez, J.~Llorca, R.~D.~Braatz, A benchmark simulator for advanced control of ethanol steam reforming, Renewable Energy 256 (2026) 124743, doi:10.1016/j.renene.2025.124743. Code: github.com/arcmateo/SSMR\_Benchmark.
\bibitem{serra} M.~Serra, C.~Ocampo-Martinez, M.~Li, J.~Llorca, Model predictive control for ethanol steam reformers with membrane separation, Int.\ J.\ Hydrogen Energy 42 (2017) 1949--1961, doi:10.1016/j.ijhydene.2016.10.110.
\bibitem{scott} J.~K.~Scott, R.~Findeisen, R.~D.~Braatz, D.~M.~Raimondo, Input design for guaranteed fault diagnosis using zonotopes, Automatica 50 (2014) 1580--1589.
\bibitem{raimondo} D.~M.~Raimondo, G.~R.~Marseglia, R.~D.~Braatz, J.~K.~Scott, Closed-loop input design for guaranteed fault diagnosis using set-valued observers, Automatica 74 (2016) 107--117.
\end{thebibliography}

\clearpage
\begin{figure}[h]\centering\includegraphics[width=.95\linewidth]{fig_operating_map_A1.pdf}\caption{Operating map, amendment A1 (fixed threshold). The frozen-threshold map is \texttt{fig\_operating\_map.pdf} in the repository.}\label{fig:map}\end{figure}
\begin{figure}[h]\centering\includegraphics[width=.9\linewidth]{fig_voi_A1.pdf}\caption{Value of information relative to hydrogen flow alone (A1).}\label{fig:voi}\end{figure}
\begin{figure}[h]\centering\includegraphics[width=.62\linewidth]{fig_m3_residuals.pdf}\includegraphics[width=.62\linewidth]{fig_m3_timeview.pdf}\caption{Worked case: catalyst versus membrane at a 5\% hydrogen drop.}\label{fig:m3}\end{figure}
\begin{figure}[h]\centering\includegraphics[width=.62\linewidth]{fig_v1_validation.pdf}\caption{Validation V1.}\label{fig:v1}\end{figure}
\end{document}
'''

sub = {k: v for k, v in N.items() if not isinstance(v, list)}
repl = {
    'ml_max_dH2': f4(N['ml_max_dH2']), 'ml_max_dIAE': f3(N['ml_max_dIAE']), 'move_cost': f'{N["move_cost"]:.4f}',
    'm3_move_sd': f'{N["m3_move_sd"]:.1f}', 'gap_ratio_cs2t': f3(N['gap_ratio_cs2t']), 'step_tau': f3(N['step_tau']),
    'step_delay': f3(N['step_delay']), 'cs1_contaminated': f'{N["cs1_contaminated"]:+.1f}',
    'V1_C': f3(N['V1_C']), 'V1_M': f'{N["V1_M"]:.4f}', 'V2_max': f'{N["V2_max"]:.5f}',
    'thC': f3(N['thC']), 'thM': f3(N['thM']), 'm3_ch4_sd': f'{N["m3_ch4_sd"]:.1f}',
    'm3_lambda_E5': f'{N["m3_lambda_E5"]:.1f}', 'm3_lambda_E5_M': f'{N["m3_lambda_E5_M"]:.1f}', 'm3_keq': f4(N['m3_keq']),
    'rank_m1_S1E': str(N['rank_m1_S1E']), 'rank_m1_S4E': str(N['rank_m1_S4E']),
    'sens_half_0': str(N['sens_half'][0]), 'sens_base': str(N['dist_m1_S1E'][2] + N['dist_m2_S1E'][2]), 'sens_double_0': str(N['sens_double'][0]), 'sens_half_1': str(N['sens_half'][1]),
    'voiA_m1_S1E_EtOH': um(N['voiA_m1_S1+E_EtOH']), 'voiA_m1_S1E_H2': um(N['voiA_m1_S1+E_H2']),
    'voiA_m2_S1E_EtOH': um(N['voiA_m2_S1+E_EtOH']), 'voiA_m2_S1E_H2': um(N['voiA_m2_S1+E_H2']),
    'voiA_m1_S4_EtOH': um(N['voiA_m1_S4_EtOH']), 'payback': f'{N["payback_min_m1"]:.0f}',
    'TABLE_ROWS': table_rows}
for c in ('STEP', 'CS1', 'CS2T', 'CS2P'):
    repl[f'{c}_dH'] = f4(fr[c]['max_dH2_pct_nominal_vs_python']); repl[f'{c}_dU'] = f4(fr[c]['max_dEtOH_pct_nominal'])
    if c != 'STEP':
        repl[f'{c}_dI'] = f3(fr[c]['IAE_rel_diff_pct']); repl[f'ml_{c}_vs_pub'] = f'{fr[c]["matlab_vs_published_pct"]:+.2f}'
tex = TEX
for k, v in repl.items():
    tex = tex.replace(f'<<{k}>>', v)
assert '<<' not in tex, [l for l in tex.splitlines() if '<<' in l][:3]
(HERE / 'note_v1.tex').write_text(tex, encoding='utf-8')
(HERE / 'NUMBERS.json').write_text(json.dumps({'raw': N, 'printed': repl}, indent=2, default=str) + '\n')
for f in ('fig_operating_map_A1', 'fig_voi_A1', 'fig_m3_residuals', 'fig_m3_timeview', 'fig_v1_validation', 'fig_operating_map', 'fig_voi'):
    shutil.copy2(D / f'{f}.pdf', HERE / f'{f}.pdf')
print('note_v1.tex written;', len(repl), 'numbers inserted')
