"""Build M1_FINAL_REPORT.md from files on disk only. Every number in the report is computed here
from: octave/comparison.json (compare.py), octave/cases/*/*/meta.json, outputs/*/result.json
(Python port, other lane), outputs/STEP/dense.csv, config.yaml and upstream control.m.
Run compare.py first. verify_report.py rebuilds and asserts."""
from pathlib import Path
import json, re
import numpy as np
import yaml

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
UP = PKG.parent / 'upstream' / 'SSMR_simulator'
CFG = yaml.safe_load((PKG / 'config.yaml').read_text())
PUB = CFG['paper_targets']
SS = {1: 2.27354e-4, 2: 2.76379e-4}
TS = 0.1


def f(x, d=4):
    return f'{x:.{d}f}'


def g(x, d=4):
    return f'{x:.{d}e}'


def py(name):
    p = PKG / 'outputs' / name / 'result.json'
    return json.loads(p.read_text()) if p.exists() else None


def build():
    comp = json.loads((HERE / 'comparison.json').read_text())
    runs = []
    for m in sorted(HERE.glob('cases/*/*/meta.json')):
        d = json.loads(m.read_text())
        rows = len(re.findall(r'^ROW ', (m.parent / 'run.log').read_text(encoding='utf-8', errors='replace'), flags=re.M)) \
            if (m.parent / 'run.log').exists() else 0
        err = re.findall(r'At t = ([0-9.e+-]+) and h = ([0-9.e+-]+)', (m.parent / 'run.log').read_text(encoding='utf-8', errors='replace')) \
            if (m.parent / 'run.log').exists() else []
        runs.append((m.parent.parent.name, m.parent.name, d.get('status'), d.get('wall_seconds'), rows, err[-1] if err else None))

    L = ['# M1 baseline: final report (native Octave cross-check of the SSMR benchmark)', '',
         'Generated by `reformer_diag/octave/build_report.py` from files on disk; checked by `verify_report.py`. '
         'Simulation only. Octave is not MATLAB. Scope: Modes 1 and 2, np = 50, the README case studies and the '
         'paper Section 5.1 ethanol step. Nothing has been sent to anyone.', '']

    # ---- bottom line
    s = comp.get('STEP_np50_p6/wsl64', {})
    c1 = comp.get('CS1_np50_p6/wsl64', {})
    ml = json.loads((PKG / 'matlab_native' / 'MATLAB_NATIVE_RESULTS.json').read_text())
    fr = ml['fresh_session_results']
    L += ['## Bottom line', '',
          f"1. **Native MATLAB reference obtained** ({ml['runtime']}): the untouched author script was run for STEP, CS1, CS2T and CS2P. "
          f"Against it, the Python port's largest H2 difference is {max(fr[c]['max_dH2_pct_nominal_vs_python'] for c in ('STEP','CS1','CS2T','CS2P')):.4f}% of nominal "
          f"and its largest IAE difference {max(fr[c]['IAE_rel_diff_pct'] for c in ('CS1','CS2T','CS2P')):.3f}%: every approved equivalence gate passes for all four cases (section 2a).",
          f"2. CS1 reproduces the paper: MATLAB IAE {fr['CS1']['IAE_matlab_mol']:.4e} mol ({fr['CS1']['matlab_vs_published_pct']:+.2f}% vs published), Python {100*(py('CS1')['tracking']['conventional_iae_mol']-PUB['CS1_iae_mol'])/PUB['CS1_iae_mol']:+.2f}%.",
          f"3. CS2T and CS2P do NOT reproduce the paper's IAE, and the authors' own code in MATLAB misses by the same amount "
          f"({fr['CS2T']['matlab_vs_published_pct']:+.2f}% and {fr['CS2P']['matlab_vs_published_pct']:+.2f}%). The discrepancy is between the released code and the paper, "
          'not in the port. For CS2T it equals one extra 0.1-min sample of startup error to within 0.03% (section 5, post-hoc).',
          "4. Reproducibility pitfall found: control.m keeps PID state in persistent variables that SSMR_simulation.m's `clear` does not reset; "
          f"running cases back to back in one MATLAB session changed CS1's IAE by {ml['contaminated_first_session']['CS1_vs_published_pct']:+.2f}% vs published. `clear control` fixes it.",
          "5. The paper's 'time constant 0.25 min' is not what a first-order-plus-dead-time fit returns (about 0.05 min); the elapsed time from the input step "
          'to 63.2% of the rise is about 0.25 min (section 6). The frozen time-constant gate stays failed.',
          '6. Octave cannot integrate the Mode 2 steam startup (NonNegative is ignored by Octave ode15s; section 4). Octave agrees with Python on Mode 1.',
          '7. M1 status: equivalence CLOSED (native MATLAB). Paper gates: CS1 PASS; CS2T, CS2P and the STEP time constant FAIL, attributed to the '
          'code-vs-paper definitions, pending the two author questions (AUTHOR_QUESTIONS_DRAFT.md, not sent).', '']
    L += ['## 2a. Equivalence against native MATLAB (primary)', '',
          'Computed inside MATLAB Online; Python traces typed in as integers (H2 x 1e10, ethanol x 1e9), checksums verified. '
          'Transcribed from the MATLAB screen (screenshots: `matlab_native/evidence/`). Fresh PID state for every closed-loop case.', '',
          '| case | max dH2 (% nominal) | max dEtOH (% nominal) | IAE MATLAB (mol) | IAE Python (mol) | IAE diff (%) | gates (0.5 / 0.5 / 1%) | MATLAB vs published |',
          '|---|---:|---:|---:|---:|---:|---|---:|']
    for c in ('STEP', 'CS1', 'CS2T', 'CS2P'):
        r = fr[c]
        ok = r['max_dH2_pct_nominal_vs_python'] <= .5 and r['max_dEtOH_pct_nominal'] <= .5 and r.get('IAE_rel_diff_pct', 0) <= 1
        L.append(f"| {c} | {r['max_dH2_pct_nominal_vs_python']:.4f} | {r['max_dEtOH_pct_nominal']:.4f} | "
                 f"{r.get('IAE_matlab_mol', float('nan')):.6e} | {r.get('IAE_python_same_grid_mol', float('nan')):.6e} | "
                 f"{r.get('IAE_rel_diff_pct', float('nan')):.3f} | {'PASS' if ok else 'FAIL'} | "
                 f"{('%+.2f%%' % r['matlab_vs_published_pct']) if 'matlab_vs_published_pct' in r else 'n/a (open loop)'} |")
    L += ['', f"Reproduce: `matlab_native/run_in_matlab_online.m`. CS2T first run vs fresh run: max |dH2| = {fr['CS2T']['first_run_vs_fresh_max_abs_dH2']} (deterministic).", '']

    # ---- runs
    L += ['## 1. Runs (all attempts kept)', '',
          '| case folder | runtime | status | wall s | intervals logged | IDA failure (t, h) |', '|---|---|---|---:|---:|---|']
    for case, rt, st, w, rows, err in runs:
        L.append(f"| {case} | {rt} | {st} | {'' if w is None else f(w, 1)} | {rows} | {'' if not err else f'{err[0]}, {err[1]}'} |")
    L += ['', 'Variants: `untouched` = author SSMR_simulation.m with only settings/paths/output patches; `p6` = plus a '
          'coloured finite-difference Jacobian of the author RHS, fixed per 0.1-min interval; `p6v3` = the same as a '
          'function ode15s calls when it wants; `p7` = p6v3 plus an emulation of the NonNegative option. Protocols: '
          '`PROTOCOL_2026-09-29_M1_native_upstream.md`, `PROTOCOL_2026-09-30_P6_solver_amendment.md` (hashed). '
          'Patch list: `PATCHES.md`.', '']

    # ---- equivalence table
    L += ['## 2b. Octave cross-check (secondary)', '',
          'Gates approved by Bosco 2026-09-30: max |dH2| <= 0.5% of nominal H2, IAE difference <= 1%, max |dEtOH| <= 0.5% of nominal ethanol. '
          'Rows matched by sample index (same display-time convention in all sources).', '',
          '| Octave run | compared with | max dH2 (% nominal) | max dEtOH (% nominal) | IAE diff (%) | rows | gate |', '|---|---|---:|---:|---:|---|---|']
    for k, r in comp.items():
        for grp in ('vs_python', 'vs_wrapper_octave'):
            for name, d in (r.get(grp) or {}).items():
                if isinstance(d, dict):
                    L.append(f"| {k} | {grp.replace('vs_', '')}: {name} | {f(d['max_dH2_pct_nominal'])} | {f(d['max_dEtOH_pct_nominal'])} | "
                             f"{f(d['iae_rel_diff_pct'])} | {d['rows_compared']} | {d['proposed_gate']} |")
    L.append('')

    # ---- STEP transient rows
    if s:
        o = np.loadtxt(HERE / 'cases' / 'STEP_np50_p6' / 'wsl64' / 'trajectory.csv', delimiter=',')
        p = np.loadtxt(PKG / 'outputs' / 'STEP' / 'trace.csv', delimiter=',', skiprows=1)
        wf = PKG / 'matlab' / 'native_outputs_jacobian_v2' / 'STEP_trace.csv'
        w = np.loadtxt(wf, delimiter=',', skiprows=1) if wf.exists() else None
        n = min(len(o), len(p))
        d = 100 * np.abs(o[:n, 1] - p[:n, 3]) / SS[1]
        big = np.where(d > 0.05)[0]
        L += ['## 3. Where STEP differs', '',
              f'Rows with |dH2| > 0.05% of nominal (Octave vs Python): {", ".join(f"t = {o[i,0]:.1f} min ({d[i]:.3f}%)" for i in big)}. '
              f'All other rows: max {f(np.delete(d, big).max(), 4)}%.']
        if w is not None:
            dw = 100 * np.abs(o[:n, 1] - w[:n, 3]) / SS[1]
            L.append(f'The two Octave runs (this lane vs the other lane, both Octave 6.4) differ from each other by up to {f(dw.max(), 3)}% '
                     f'at t = {o[dw.argmax(), 0]:.1f} min.')
        L += ['Cause: upstream records H2 as the global F_H2 left by the LAST right-hand-side call ode15s made in the interval, '
              'not the value at the interval end point. In the steepest 0.1 min of the rise that number depends on the '
              "solver's step path, so implementations differ there by about half a percent. The frozen gate is kept; this "
              'is reported as a narrow FAIL with its cause.', '']

    # ---- Mode 2
    L += ['## 4. Mode 2 in Octave: why it could not be run', '',
          '- Neither installed Octave ode15s.m (6.4.0, 11.3.0) contains any NonNegative handling (text search of both files); '
          "the author script's `'NonNegative', 1:8*2*np` is silently ignored. MATLAB honours it.",
          '- Untouched script: interval 1 of 101 took 293 s (Octave 6.4) and 617 s (Octave 11.3); interval 2 did not finish '
          'in over 25 min of awake time. Upstream RHS costs 0.11 s per call in Octave; each default Jacobian needs 800 calls.',
          '- Supplied-Jacobian and NonNegative-emulation variants fail in interval 2 (ethanol first enters the steam-filled '
          'reactor) with IDA "corrector convergence failed repeatedly or with |h| = hmin"; failure times are in the run table.',
          '- The Python port also needed a documented positivity extension to pass this startup (other lane, '
          '`NUMERICAL_EXTENSION_PROTOCOL.md`). No non-MATLAB solver tried so far integrates this startup as released.',
          '- Consequence: Mode 2 equivalence against a native run is an open gap that needs MATLAB (MATLAB Online or an '
          'author-supplied trace).', '']

    # ---- IAE offset
    L += ['## 5. The Mode 2 IAE gap is one sample of startup error (post-hoc)', '',
          '| case | Python IAE (mol) | published | gap | set-point x 0.1 min | gap / (set-point x 0.1) | Python + one sample vs published |',
          '|---|---:|---:|---:|---:|---:|---:|']
    for case, name, mode in (('CS1', 'CS1', 1), ('CS2T', 'CS2T_extended', 2), ('CS2P', 'CS2P_extended', 2)):
        r = py(name)
        if not r:
            continue
        v = r['tracking']['conventional_iae_mol']; pub = PUB[f'{case}_iae_mol']; one = SS[mode] * TS
        L.append(f'| {case} ({name}) | {g(v)} | {g(pub, 2)} | {g(pub - v)} | {g(one)} | {f((pub - v) / one, 3)} | {100 * (v + one - pub) / pub:+.2f}% |')
    L += ['', 'CS2T and CS2P start from the steam-only state, where H2 is zero and the error equals the full set-point. '
          'One extra 0.1-min sample of that error, as a time basis starting one sample earlier or an integration '
          'to 10.1 min would add, closes the CS2T gap almost exactly. CS1 starts at steady state, so the same extra '
          'sample adds almost nothing, consistent with its near-zero gap. CS2P is closed less well. This pattern was '
          'found after seeing results; it is a question for the first author, not a passed gate.', '']

    # ---- STEP time constant
    st = py('STEP')
    dense = np.loadtxt(PKG / 'outputs' / 'STEP' / 'dense.csv', delimiter=',', skiprows=1)
    hdr = (PKG / 'outputs' / 'STEP' / 'dense.csv').read_text().splitlines()[0].split(',')
    col = hdr.index('hydrogen_mol_min')
    t, y = dense[:, hdr.index('physical_min')], dense[:, col]
    y0, yf = y[(t >= 1.8) & (t <= 2.0)].mean(), y[(t >= 3.8) & (t <= 4.0)].mean()
    thr = y0 + 0.632 * (yf - y0)
    i = int(np.argmax((t > 2.0) & (y >= thr)))
    tc = t[i - 1] + (thr - y[i - 1]) * (t[i] - t[i - 1]) / (y[i] - y[i - 1])
    ctrl = (UP / 'control.m').read_text()
    tao = re.search(r'tao\s*=\s*([0-9.]+)', ctrl).group(1)
    L += ['## 6. The "time constant 0.25 min"', '',
          f"- FOPDT fit (frozen method) on the Python dense trace: tau {f(st['dynamics']['tau_min'], 4)} min, dead time "
          f"{f(st['dynamics']['delay_min'], 4)} min; gate vs 0.25 min: {st['dynamics']['status']} (unchanged).",
          f'- Elapsed time from the input step (t = 2 min) to 63.2% of the rise, Python dense trace (column `{hdr[col]}`): {f(tc - 2.0, 4)} min.',
          f'- Upstream control.m sets `tao = {tao}` and uses the classical Ziegler-Nichols ultimate-cycle formulas '
          '(Kp = 0.6 Ku, Ki = 1.2 Ku/Pu, Kd = 3 Ku Pu/40, then detuned), where that value plays the role of the '
          'ultimate period.',
          '- Reading: the paper may mean elapsed time to 63.2% including dead time. Post-hoc; question for the author.', '']

    # ---- gates
    cs1 = py('CS1')
    L += ['## 7. M1 gate status', '', '| gate | status | evidence |', '|---|---|---|',
          f"| CS1 IAE within 2% of paper (Python) | {cs1['tracking']['status']} | {f(cs1['tracking']['relative_deviation_pct'], 3)}% |",
          f"| CS2T IAE within 2% (Python, positivity extension) | {py('CS2T_extended')['tracking']['status']} | {f(py('CS2T_extended')['tracking']['relative_deviation_pct'], 2)}% |",
          f"| CS2P IAE within 2% (Python, positivity extension) | {py('CS2P_extended')['tracking']['status']} | {f(py('CS2P_extended')['tracking']['relative_deviation_pct'], 2)}% |",
          f"| STEP time constant within 5% of 0.25 min | {st['dynamics']['status']} | FOPDT tau {f(st['dynamics']['tau_min'], 4)} min |"]
    if c1:
        L.append(f"| CS1 IAE within 2% (author script, Octave) | {c1['vs_paper']['status']} | {f(c1['vs_paper']['relative_deviation_pct'], 3)}% |")
        L.append(f"| CS1 Octave vs Python equivalence | {c1['vs_python']['CS1']['proposed_gate']} | max dH2 {f(c1['vs_python']['CS1']['max_dH2_pct_nominal'])}% |")
    if s:
        L.append(f"| STEP Octave vs Python equivalence | {s['vs_python']['STEP']['proposed_gate']} | max dH2 {f(s['vs_python']['STEP']['max_dH2_pct_nominal'], 3)}% |")
    L += [f"| Native MATLAB vs Python equivalence (all four cases) | PASS | section 2a |",
          '| Mode 2 in Octave | NOT RUNNABLE (startup) | section 4 |',
          '| np = 200 native runs | NOT RUN (time) | MATLAB would allow it; left for the release checklist |', '']
    L += ['## 8. What remains before M1 can close', '',
          '1. Native MATLAB traces now exist (done 2026-09-30).',
          '2. The first author confirms the IAE time basis and the meaning of "time constant 0.25 min" (draft questions: '
          '`AUTHOR_QUESTIONS_DRAFT.md`, not sent).',
          '3. If both answers match the readings above, re-run the frozen gates with the confirmed definitions, as a '
          'dated amendment; the current failures stay on the record.',
          '4. Until then, no identifiability or diagnosis results (Bosco condition 3).', '']
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    text = build()
    (HERE / 'M1_FINAL_REPORT.md').write_text(text, encoding='utf-8')
    print(text)
